//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZazBoy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZazBoy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonBackground {
            get {
                object obj = ResourceManager.GetObject("ButtonBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonPressedBackground {
            get {
                object obj = ResourceManager.GetObject("ButtonPressedBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CPUIcon {
            get {
                object obj = ResourceManager.GetObject("CPUIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DebugText {
            get {
                object obj = ResourceManager.GetObject("DebugText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HideNavBar {
            get {
                object obj = ResourceManager.GetObject("HideNavBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;unprefixed&quot;: {
        ///		&quot;0x00&quot;: {
        ///			&quot;mnemonic&quot;: &quot;NOP&quot;,
        ///			&quot;bytes&quot;: 1,
        ///			&quot;cycles&quot;: [
        ///				4
        ///			],
        ///			&quot;operands&quot;: [],
        ///			&quot;immediate&quot;: true,
        ///			&quot;flags&quot;: {
        ///				&quot;Z&quot;: &quot;-&quot;,
        ///				&quot;N&quot;: &quot;-&quot;,
        ///				&quot;H&quot;: &quot;-&quot;,
        ///				&quot;C&quot;: &quot;-&quot;
        ///			}
        ///		},
        ///		&quot;0x01&quot;: {
        ///			&quot;mnemonic&quot;: &quot;LD&quot;,
        ///			&quot;bytes&quot;: 3,
        ///			&quot;cycles&quot;: [
        ///				12
        ///			],
        ///			&quot;operands&quot;: [
        ///				{
        ///					&quot;name&quot;: &quot;BC&quot;,
        ///					&quot;immediate&quot;: true
        ///				},
        ///				{
        ///					&quot;name&quot;: &quot;d16&quot;,
        ///					&quot;bytes&quot;: 2,
        ///					&quot;immediate&quot;: true
        ///				}
        ///			],
        ///			&quot;immediate&quot;: true,
        ///			&quot;flags&quot;: {
        ///				&quot;Z&quot;: &quot;-&quot;,
        ///				&quot;N&quot;: &quot;-&quot;,
        ///				&quot;H&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InstructionDatabase {
            get {
                return ResourceManager.GetString("InstructionDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PauseText {
            get {
                object obj = ResourceManager.GetObject("PauseText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PowerText {
            get {
                object obj = ResourceManager.GetObject("PowerText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ResumeText {
            get {
                object obj = ResourceManager.GetObject("ResumeText", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
